# common_name
common_name <- tibble::tribble(
  ~speciescode,                    ~common_name,
  "A001",            "Red-throated Diver",
  "A002",          "Black-throated Diver",
  "A003",          "Great Northern Diver",
  "A004",                  "Little Grebe",
  "A005",           "Great Crested Grebe",
  "A006",              "Red-necked Grebe",
  "A007",                  "Horned Grebe",
  "A008",            "Black-necked Grebe",
  "A009",                        "Fulmar",
  "A013",               "Manx Shearwater",
  "A014",         "European Storm-petrel",
  "A016",               "Northern Gannet",
  "A021",                 "Great Bittern",
  "A022",                "Little Bittern",
  "A025",                  "Cattle Egret",
  "A026",                  "Little Egret",
  "A028",                    "Grey Heron",
  "A034",            "Eurasian Spoonbill",
  "A036",                     "Mute Swan",
  "A037",                   "Tundra Swan",
  "A038",                  "Whooper Swan",
  "A040-B",             "Pink-footed Goose",
  "A043",                 "Greylag Goose",
  "A044-X",                  "Canada Goose",
  "A045-A",                "Barnacle Goose",
  "A045-B",                "Barnacle Goose",
  "A045-X",                "Barnacle Goose",
  "A048",               "Common Shelduck",
  "A052",                   "Common Teal",
  "A053",                       "Mallard",
  "A054",              "Northern Pintail",
  "A058-X",           "Red-crested Pochard",
  "A059",                "Common Pochard",
  "A061",                   "Tufted Duck",
  "A062",                 "Greater Scaup",
  "A063",                  "Common Eider",
  "A064",              "Long-tailed Duck",
  "A066",                 "Velvet Scoter",
  "A067",              "Common Goldeneye",
  "A069",        "Red-breasted Merganser",
  "A070",              "Common Merganser",
  "A072",        "European Honey-buzzard",
  "A074",                      "Red Kite",
  "A075",            "White-tailed Eagle",
  "A081",         "Western Marsh-harrier",
  "A082",                   "Hen Harrier",
  "A084",             "Montagu's Harrier",
  "A087",                "Common Buzzard",
  "A091",                  "Golden Eagle",
  "A094",                        "Osprey",
  "A096",                "Common Kestrel",
  "A098",                        "Merlin",
  "A099",                "Eurasian Hobby",
  "A103",              "Peregrine Falcon",
  "A110-X",          "Red-legged Partridge",
  "A113",                  "Common Quail",
  "A115-X",               "Common Pheasant",
  "A118",                    "Water Rail",
  "A119",                 "Spotted Crake",
  "A122",                     "Corncrake",
  "A123",                "Common Moorhen",
  "A125",                   "Common Coot",
  "A127",                  "Common Crane",
  "A129",                 "Great Bustard",
  "A130",        "Eurasian Oystercatcher",
  "A131",            "Black-winged Stilt",
  "A132",                   "Pied Avocet",
  "A133",           "Eurasian Thick-knee",
  "A136",          "Little Ringed Plover",
  "A137",          "Common Ringed Plover",
  "A140",        "Eurasian Golden Plover",
  "A141",                   "Grey Plover",
  "A142",              "Northern Lapwing",
  "A143",                      "Red Knot",
  "A144",                    "Sanderling",
  "A146",              "Temminck's Stint",
  "A148",              "Purple Sandpiper",
  "A149",                        "Dunlin",
  "A152",                    "Jack Snipe",
  "A153",                  "Common Snipe",
  "A155",             "Eurasian Woodcock",
  "A156",             "Black-tailed Godwit",
  "A157",             "Bar-tailed Godwit",
  "A158",                      "Whimbrel",
  "A161",              "Spotted Redshank",
  "A162",               "Common Redshank",
  "A164",             "Common Greenshank",
  "A165",               "Green Sandpiper",
  "A166",                "Wood Sandpiper",
  "A168",              "Common Sandpiper",
  "A169",               "Ruddy Turnstone",
  "A170",          "Red-necked Phalarope",
  "A173",              "Parasitic Jaeger",
  "A175",                    "Great Skua",
  "A176",            "Mediterranean Gull",
  "A179",             "Black-headed Gull",
  "A182",                      "Mew Gull",
  "A185",                      "Iceland Gull",
  "A186",                      "Glaucous Gull",
  "A187",       "Great Black-backed Gull",
  "A188",        "Black-legged Kittiwake",
  "A192",                  "Roseate Tern",
  "A193",                   "Common Tern",
  "A194",                   "Arctic Tern",
  "A197",                    "Black Tern",
  "A200",                     "Razorbill",
  "A202",               "Black Guillemot",
  "A203",               "Little Auk",
  "A204",               "Atlantic Puffin",
  "A206-X",                   "Rock Pigeon",
  "A206",                   "Rock Pigeon",
  "A207",                    "Stock Dove",
  "A209",        "Eurasian Collared-dove",
  "A210",          "European Turtle-dove",
  "A212",                 "Common Cuckoo",
  "A213",                      "Barn Owl",
  "A215-X",                     "Eagle Owl",
  "A218-X",                    "Little Owl",
  "A219",                     "Tawny Owl",
  "A221",                "Long-eared Owl",
  "A222",               "Short-eared Owl",
  "A224",             "Eurasian Nightjar",
  "A226",                  "Common Swift",
  "A229",             "Common Kingfisher",
  "A233",              "Eurasian Wryneck",
  "A246",                     "Wood Lark",
  "A247",              "Eurasian Skylark",
  "A249",                   "Sand Martin",
  "A251",                  "Barn Swallow",
  "A256",                    "Tree Pipit",
  "A257",                  "Meadow Pipit",
  "A260",                "Yellow Wagtail",
  "A261",                  "Grey Wagtail",
  "A262",                 "White Wagtail",
  "A264",         "White-throated Dipper",
  "A266",                "Hedge Accentor",
  "A269",                "European Robin",
  "A271",            "Common Nightingale",
  "A273",                "Black Redstart",
  "A274",               "Common Redstart",
  "A275",                      "Whinchat",
  "A276",              "Common Stonechat",
  "A277",             "Northern Wheatear",
  "A282",                    "Ring Ouzel",
  "A283",            "Eurasian Blackbird",
  "A284",                     "Fieldfare",
  "A285",                   "Song Thrush",
  "A286",                       "Redwing",
  "A287",                 "Mistle Thrush",
  "A288",               "Cetti's Warbler",
  "A290",    "Common Grasshopper-warbler",
  "A292",                "Savi's Warbler",
  "A294",               "Aquatic Warbler",
  "A295",                 "Sedge Warbler",
  "A296",                 "Marsh Warbler",
  "A297",         "Eurasian Reed-warbler",
  "A302",              "Dartford Warbler",
  "A309",            "Common Whitethroat",
  "A310",                "Garden Warbler",
  "A311",                      "Blackcap",
  "A314",                  "Wood Warbler",
  "A316",                "Willow Warbler",
  "A317",                     "Goldcrest",
  "A318",                     "Firecrest",
  "A319",            "Spotted Flycatcher",
  "A322",      "European Pied Flycatcher",
  "A323",            "Bearded Parrotbill",
  "A324",               "Long-tailed Tit",
  "A330",                     "Great Tit",
  "A332",                 "Wood Nuthatch",
  "A334",          "Eurasian Treecreeper",
  "A337",        "Eurasian Golden Oriole",
  "A338",             "Red-backed Shrike",
  "A342",                  "Eurasian Jay",
  "A343",           "Black-billed Magpie",
  "A346",             "Red-billed Chough",
  "A347",              "Eurasian Jackdaw",
  "A348",                          "Rook",
  "A349",                  "Carrion Crow",
  "A350",                  "Common Raven",
  "A351",               "Common Starling",
  "A356",         "Eurasian Tree Sparrow",
  "A360",                     "Brambling",
  "A363",           "European Greenfinch",
  "A364",            "European Goldfinch",
  "A369",                 "Red Crossbill",
  "A370",              "Parrot Crossbill",
  "A372",            "Eurasian Bullfinch",
  "A373",                      "Hawfinch",
  "A374",              "Lapland Longspur",
  "A375",                  "Snow Bunting",
  "A376",                  "Yellowhammer",
  "A377",                  "Cirl Bunting",
  "A381",                  "Reed Bunting",
  "A383",                  "Corn Bunting",
  "A391",               "Great Cormorant",
  "A394",  "European White-fronted Goose",
  "A395", "Greenland White-fronted Goose",
  "A397-X",                "Ruddy Shelduck",
  "A434",                   "Winter Wren",
  "A451",            "Scottish Crossbill",
  "A460-X",                   "Wild Turkey",
  "A463",              "Willow Ptarmigan",
  "A466-A",                        "Dunlin",
  "A472",                      "Coal Tit",
  "A474",                "Common Redpoll",
  "A476",               "Eurasian Linnet",
  "A477",                         "Twite",
  "A478",               "Eurasian Siskin",
  "A483",                      "Blue Tit",
  "A489",      "Lesser Black-backed Gull",
  "A492",                    "Willow Tit",
  "A493",                     "Marsh Tit",
  "A497",                   "Crested Tit",
  "A502",            "White-billed Diver",
  "A553-X",                 "Mandarin Duck",
  "A556-X",                    "Snow Goose",
  "A557-X",               "Golden Pheasant",
  "A558-X",             "Reeves's Pheasant",
  "A572",             "Common Chiffchaff",
  "A574",            "Lesser Whitethroat",
  "A614-A",           "Black-tailed Godwit",
  "A616",           "Black-tailed Godwit",
  "A620",                 "House Sparrow",
  "A644",                "Grey Partridge",
  "A657",            "Eurasian Chaffinch",
  "A658",      "Great Spotted Woodpecker",
  "A659",          "Western Capercaillie",
  "A666",                    "Rock Pipit",
  "A674-A",                   "Brent Goose",
  "A674-B",                   "Brent Goose",
  "A675",                   "Brent Goose",
  "A676",                   "Winter Wren",
  "A681",                "Lesser Redpoll",
  "A683",               "Great Cormorant",
  "A684",                 "European Shag",
  "A687",            "Common Wood-pigeon",
  "A693",           "Balearic Shearwater",
  "A701",                    "Bean Goose",
  "A702",                    "Bean Goose",
  "A711",              "Willow Ptarmigan",
  "A727",             "Eurasian Dotterel",
  "A738",         "Northern House-martin",
  "A747-X",                    "Black Swan",
  "A748-X",                "Egyptian Goose",
  "A749-X",                     "Wood Duck",
  "A750-X",                    "Ruddy Duck",
  "A751-X",                  "Muscovy Duck",
  "A755-X",       "Lady Amherst's Pheasant",
  "A756-X",                "Indian Peafowl",
  "A757-X",           "Helmeted Guineafowl",
  "A760-X",          "Rose-ringed Parakeet",
  "A761-X",                 "Monk Parakeet",
  "A767",                          "Smew",
  "A768",               "Eurasian Curlew",
  "A773",             "Great White Egret",
  "A844-X",                 "Emperor Goose",
  "A845-X",              "Bar-headed Goose",
  "A846-X",               "Red-tailed Hawk",
  "A847-X",                 "Harris's Hawk",
  "A848-X",           "Rosy-faced Lovebird",
  "A854",          "Leach's Storm-petrel",
  "A855",               "Eurasian Wigeon",
  "A856",                      "Garganey",
  "A857",             "Northern Shoveler",
  "A861",                          "Ruff",
  "A862",                   "Little Gull",
  "A863",                 "Sandwich Tern",
  "A866",     "Eurasian Green Woodpecker",
  "A869",     "Lesser Spotted Woodpecker",
  "A877",                  "Black Grouse",
  "A885",                   "Little Tern",
  "A887",              "Common Guillemot",
  "A889",                       "Gadwall",
  "A891",                "Rock Ptarmigan",
  "A895",                  "Herring Gull",
  "A898",          "Eurasian Sparrowhawk",
  "A899",              "Northern Goshawk",
  "A900",                 "Common Scoter"
)

# information_species_look_up
url <- "http://biodiversity.eionet.europa.eu/activities/Reporting/Article_12/Reports_2019/Files_2019/art12_checklist_v2_update20180616.xls"
dest_file <- "art12_checklist_v2_update20180616.xls"
curl::curl_download(url, dest_file)
information_species_look_up <- readxl::read_excel(dest_file, sheet = "Art12 checklist") %>% 
  janitor::clean_names() %>% 
  dplyr::filter(country == "UK") %>% 
  dplyr::rename(speciescode = species_code,
                speciesname = species_name) %>%
  dplyr::left_join(common_name, by = "speciescode") %>% 
  dplyr::mutate(season = dplyr::case_when 
                (
                  stringr::str_to_lower(season) == "b" ~ "breeding",
                  stringr::str_to_lower(season) == "w" ~ "winter",
                  stringr::str_to_lower(season) == "p" ~ "passage",
                  TRUE ~ season
                )) %>%
  dplyr::mutate(occurrence = dplyr::case_when 
                (
                  stringr::str_to_lower(occurrence) == "pre" ~ "present",
                  stringr::str_to_lower(occurrence) == "arr" ~ "colonised",
                  stringr::str_to_lower(occurrence) == "exba" ~ "extinct",
                  TRUE ~ occurrence
                )) %>%
  dplyr::mutate(recommended_unit = dplyr::case_when 
                (
                  stringr::str_to_lower(recommended_unit) == "bfemales" ~ "breeding females",
                  stringr::str_to_lower(recommended_unit) == "cmales" ~ "calling males",
                  stringr::str_to_lower(recommended_unit) == "i" ~ "individuals",
                  stringr::str_to_lower(recommended_unit) == "males" ~ "males",  
                  stringr::str_to_lower(recommended_unit) == "p" ~ "pairs",    
                  TRUE ~ recommended_unit
                )) %>% 
  dplyr::select(speciescode,
                euringcode,
                speciesname,
                sub_unit,
                common_name,
                season,
                occurrence,
                recommended_unit) %>% 
  dplyr::arrange(speciesname, sub_unit)