library(magrittr)

# common_name
common_name <- tibble::tribble(
  ~speciescode,                    ~common_name,
  "A001",            "Red-throated Diver",
  "A002",          "Black-throated Diver",
  "A003",          "Great Northern Diver",
  "A004",                  "Little Grebe",
  "A005",           "Great Crested Grebe",
  "A006",              "Red-necked Grebe",
  "A007",                  "Horned Grebe",
  "A008",            "Black-necked Grebe",
  "A009",                        "Fulmar",
  "A013",               "Manx Shearwater",
  "A014",         "European Storm-petrel",
  "A016",               "Northern Gannet",
  "A021",                 "Great Bittern",
  "A022",                "Little Bittern",
  "A025",                  "Cattle Egret",
  "A026",                  "Little Egret",
  "A028",                    "Grey Heron",
  "A034",            "Eurasian Spoonbill",
  "A036",                     "Mute Swan",
  "A037",                   "Tundra Swan",
  "A038",                  "Whooper Swan",
  "A040-B",             "Pink-footed Goose",
  "A043",                 "Greylag Goose",
  "A044-X",                  "Canada Goose",
  "A045-A",                "Barnacle Goose",
  "A045-B",                "Barnacle Goose",
  "A045-X",                "Barnacle Goose",
  "A048",               "Common Shelduck",
  "A052",                   "Common Teal",
  "A053",                       "Mallard",
  "A054",              "Northern Pintail",
  "A058-X",           "Red-crested Pochard",
  "A059",                "Common Pochard",
  "A061",                   "Tufted Duck",
  "A062",                 "Greater Scaup",
  "A063",                  "Common Eider",
  "A064",              "Long-tailed Duck",
  "A066",                 "Velvet Scoter",
  "A067",              "Common Goldeneye",
  "A069",        "Red-breasted Merganser",
  "A070",              "Common Merganser",
  "A072",        "European Honey-buzzard",
  "A074",                      "Red Kite",
  "A075",            "White-tailed Eagle",
  "A081",         "Western Marsh-harrier",
  "A082",                   "Hen Harrier",
  "A084",             "Montagu's Harrier",
  "A087",                "Common Buzzard",
  "A091",                  "Golden Eagle",
  "A094",                        "Osprey",
  "A096",                "Common Kestrel",
  "A098",                        "Merlin",
  "A099",                "Eurasian Hobby",
  "A103",              "Peregrine Falcon",
  "A110-X",          "Red-legged Partridge",
  "A113",                  "Common Quail",
  "A115-X",               "Common Pheasant",
  "A118",                    "Water Rail",
  "A119",                 "Spotted Crake",
  "A122",                     "Corncrake",
  "A123",                "Common Moorhen",
  "A125",                   "Common Coot",
  "A127",                  "Common Crane",
  "A129",                 "Great Bustard",
  "A130",        "Eurasian Oystercatcher",
  "A131",            "Black-winged Stilt",
  "A132",                   "Pied Avocet",
  "A133",           "Eurasian Thick-knee",
  "A136",          "Little Ringed Plover",
  "A137",          "Common Ringed Plover",
  "A140",        "Eurasian Golden Plover",
  "A141",                   "Grey Plover",
  "A142",              "Northern Lapwing",
  "A143",                      "Red Knot",
  "A144",                    "Sanderling",
  "A146",              "Temminck's Stint",
  "A148",              "Purple Sandpiper",
  "A149",                        "Dunlin",
  "A152",                    "Jack Snipe",
  "A153",                  "Common Snipe",
  "A155",             "Eurasian Woodcock",
  "A156",             "Black-tailed Godwit",
  "A157",             "Bar-tailed Godwit",
  "A158",                      "Whimbrel",
  "A161",              "Spotted Redshank",
  "A162",               "Common Redshank",
  "A164",             "Common Greenshank",
  "A165",               "Green Sandpiper",
  "A166",                "Wood Sandpiper",
  "A168",              "Common Sandpiper",
  "A169",               "Ruddy Turnstone",
  "A170",          "Red-necked Phalarope",
  "A173",              "Parasitic Jaeger",
  "A175",                    "Great Skua",
  "A176",            "Mediterranean Gull",
  "A179",             "Black-headed Gull",
  "A182",                      "Mew Gull",
  "A185",                      "Iceland Gull",
  "A186",                      "Glaucous Gull",
  "A187",       "Great Black-backed Gull",
  "A188",        "Black-legged Kittiwake",
  "A192",                  "Roseate Tern",
  "A193",                   "Common Tern",
  "A194",                   "Arctic Tern",
  "A197",                    "Black Tern",
  "A200",                     "Razorbill",
  "A202",               "Black Guillemot",
  "A203",               "Little Auk",
  "A204",               "Atlantic Puffin",
  "A206-X",                   "Rock Pigeon",
  "A206",                   "Rock Pigeon",
  "A207",                    "Stock Dove",
  "A209",        "Eurasian Collared-dove",
  "A210",          "European Turtle-dove",
  "A212",                 "Common Cuckoo",
  "A213",                      "Barn Owl",
  "A215-X",                     "Eagle Owl",
  "A218-X",                    "Little Owl",
  "A219",                     "Tawny Owl",
  "A221",                "Long-eared Owl",
  "A222",               "Short-eared Owl",
  "A224",             "Eurasian Nightjar",
  "A226",                  "Common Swift",
  "A229",             "Common Kingfisher",
  "A233",              "Eurasian Wryneck",
  "A246",                     "Wood Lark",
  "A247",              "Eurasian Skylark",
  "A249",                   "Sand Martin",
  "A251",                  "Barn Swallow",
  "A256",                    "Tree Pipit",
  "A257",                  "Meadow Pipit",
  "A260",                "Yellow Wagtail",
  "A261",                  "Grey Wagtail",
  "A262",                 "White Wagtail",
  "A264",         "White-throated Dipper",
  "A266",                "Hedge Accentor",
  "A269",                "European Robin",
  "A271",            "Common Nightingale",
  "A273",                "Black Redstart",
  "A274",               "Common Redstart",
  "A275",                      "Whinchat",
  "A276",              "Common Stonechat",
  "A277",             "Northern Wheatear",
  "A282",                    "Ring Ouzel",
  "A283",            "Eurasian Blackbird",
  "A284",                     "Fieldfare",
  "A285",                   "Song Thrush",
  "A286",                       "Redwing",
  "A287",                 "Mistle Thrush",
  "A288",               "Cetti's Warbler",
  "A290",    "Common Grasshopper-warbler",
  "A292",                "Savi's Warbler",
  "A294",               "Aquatic Warbler",
  "A295",                 "Sedge Warbler",
  "A296",                 "Marsh Warbler",
  "A297",         "Eurasian Reed-warbler",
  "A302",              "Dartford Warbler",
  "A309",            "Common Whitethroat",
  "A310",                "Garden Warbler",
  "A311",                      "Blackcap",
  "A314",                  "Wood Warbler",
  "A316",                "Willow Warbler",
  "A317",                     "Goldcrest",
  "A318",                     "Firecrest",
  "A319",            "Spotted Flycatcher",
  "A322",      "European Pied Flycatcher",
  "A323",            "Bearded Parrotbill",
  "A324",               "Long-tailed Tit",
  "A330",                     "Great Tit",
  "A332",                 "Wood Nuthatch",
  "A334",          "Eurasian Treecreeper",
  "A337",        "Eurasian Golden Oriole",
  "A338",             "Red-backed Shrike",
  "A342",                  "Eurasian Jay",
  "A343",           "Black-billed Magpie",
  "A346",             "Red-billed Chough",
  "A347",              "Eurasian Jackdaw",
  "A348",                          "Rook",
  "A349",                  "Carrion Crow",
  "A350",                  "Common Raven",
  "A351",               "Common Starling",
  "A356",         "Eurasian Tree Sparrow",
  "A360",                     "Brambling",
  "A363",           "European Greenfinch",
  "A364",            "European Goldfinch",
  "A369",                 "Red Crossbill",
  "A370",              "Parrot Crossbill",
  "A372",            "Eurasian Bullfinch",
  "A373",                      "Hawfinch",
  "A374",              "Lapland Longspur",
  "A375",                  "Snow Bunting",
  "A376",                  "Yellowhammer",
  "A377",                  "Cirl Bunting",
  "A381",                  "Reed Bunting",
  "A383",                  "Corn Bunting",
  "A391",               "Great Cormorant",
  "A394",  "European White-fronted Goose",
  "A395", "Greenland White-fronted Goose",
  "A397-X",                "Ruddy Shelduck",
  "A434",                   "Winter Wren",
  "A451",            "Scottish Crossbill",
  "A460-X",                   "Wild Turkey",
  "A463",              "Willow Ptarmigan",
  "A466-A",                        "Dunlin",
  "A472",                      "Coal Tit",
  "A474",                "Common Redpoll",
  "A476",               "Eurasian Linnet",
  "A477",                         "Twite",
  "A478",               "Eurasian Siskin",
  "A483",                      "Blue Tit",
  "A489",      "Lesser Black-backed Gull",
  "A492",                    "Willow Tit",
  "A493",                     "Marsh Tit",
  "A497",                   "Crested Tit",
  "A502",            "White-billed Diver",
  "A553-X",                 "Mandarin Duck",
  "A556-X",                    "Snow Goose",
  "A557-X",               "Golden Pheasant",
  "A558-X",             "Reeves's Pheasant",
  "A572",             "Common Chiffchaff",
  "A574",            "Lesser Whitethroat",
  "A614-A",           "Black-tailed Godwit",
  "A616",           "Black-tailed Godwit",
  "A620",                 "House Sparrow",
  "A644",                "Grey Partridge",
  "A657",            "Eurasian Chaffinch",
  "A658",      "Great Spotted Woodpecker",
  "A659",          "Western Capercaillie",
  "A666",                    "Rock Pipit",
  "A674-A",                   "Brent Goose",
  "A674-B",                   "Brent Goose",
  "A675",                   "Brent Goose",
  "A676",                   "Winter Wren",
  "A681",                "Lesser Redpoll",
  "A683",               "Great Cormorant",
  "A684",                 "European Shag",
  "A687",            "Common Wood-pigeon",
  "A693",           "Balearic Shearwater",
  "A701",                    "Bean Goose",
  "A702",                    "Bean Goose",
  "A711",              "Willow Ptarmigan",
  "A727",             "Eurasian Dotterel",
  "A738",         "Northern House-martin",
  "A747-X",                    "Black Swan",
  "A748-X",                "Egyptian Goose",
  "A749-X",                     "Wood Duck",
  "A750-X",                    "Ruddy Duck",
  "A751-X",                  "Muscovy Duck",
  "A755-X",       "Lady Amherst's Pheasant",
  "A756-X",                "Indian Peafowl",
  "A757-X",           "Helmeted Guineafowl",
  "A760-X",          "Rose-ringed Parakeet",
  "A761-X",                 "Monk Parakeet",
  "A767",                          "Smew",
  "A768",               "Eurasian Curlew",
  "A773",             "Great White Egret",
  "A844-X",                 "Emperor Goose",
  "A845-X",              "Bar-headed Goose",
  "A846-X",               "Red-tailed Hawk",
  "A847-X",                 "Harris's Hawk",
  "A848-X",           "Rosy-faced Lovebird",
  "A854",          "Leach's Storm-petrel",
  "A855",               "Eurasian Wigeon",
  "A856",                      "Garganey",
  "A857",             "Northern Shoveler",
  "A861",                          "Ruff",
  "A862",                   "Little Gull",
  "A863",                 "Sandwich Tern",
  "A866",     "Eurasian Green Woodpecker",
  "A869",     "Lesser Spotted Woodpecker",
  "A877",                  "Black Grouse",
  "A885",                   "Little Tern",
  "A887",              "Common Guillemot",
  "A889",                       "Gadwall",
  "A891",                "Rock Ptarmigan",
  "A895",                  "Herring Gull",
  "A898",          "Eurasian Sparrowhawk",
  "A899",              "Northern Goshawk",
  "A900",                 "Common Scoter"
)
  
# information_species_look_up
url <- "http://biodiversity.eionet.europa.eu/activities/Reporting/Article_12/Reports_2019/Files_2019/art12_checklist_v2_update20180616.xls"
dest_file <- "art12_checklist_v2_update20180616.xls"
curl::curl_download(url, dest_file)
information_species_look_up <- readxl::read_excel(dest_file, sheet = "Art12 checklist") %>% 
  janitor::clean_names() %>% 
  dplyr::filter(country == "UK") %>% 
  dplyr::rename(speciescode = species_code,
                speciesname = species_name) %>%
  dplyr::left_join(common_name, by = "speciescode") %>% 
  dplyr::mutate(season = dplyr::case_when 
                (
                  stringr::str_to_lower(season) == "b" ~ "breeding",
                  stringr::str_to_lower(season) == "w" ~ "winter",
                  stringr::str_to_lower(season) == "p" ~ "passage",
                  TRUE ~ season
                )) %>%
  dplyr::mutate(occurrence = dplyr::case_when 
                (
                  stringr::str_to_lower(occurrence) == "pre" ~ "present",
                  stringr::str_to_lower(occurrence) == "arr" ~ "colonised",
                  stringr::str_to_lower(occurrence) == "exba" ~ "extinct",
                  TRUE ~ occurrence
                )) %>%
  dplyr::mutate(recommended_unit = dplyr::case_when 
                (
                  stringr::str_to_lower(recommended_unit) == "bfemales" ~ "breeding females",
                  stringr::str_to_lower(recommended_unit) == "cmales" ~ "calling males",
                  stringr::str_to_lower(recommended_unit) == "i" ~ "individuals",
                  stringr::str_to_lower(recommended_unit) == "males" ~ "males",  
                  stringr::str_to_lower(recommended_unit) == "p" ~ "pairs",    
                  TRUE ~ recommended_unit
                )) %>% 
  dplyr::select(speciescode,
                euringcode,
                speciesname,
                sub_unit,
                common_name,
                season,
                occurrence,
                recommended_unit) %>% 
  dplyr::arrange(speciesname, sub_unit)

# information_common_name_look_up
information_common_name_look_up <- tibble::tribble(
  ~speciescode,                                 ~common_name,                                                    ~additional_info, ~match,
  "A294",                            "Aquatic Warbler",                                                                  NA,  "yes",
  "A194",                                "Arctic Tern",                                                                  NA,  "yes",
  "A204",                            "Atlantic Puffin",                                                                  NA,  "yes",
  "A693",                        "Balearic Shearwater",                                                                  NA,  "yes",
  "A845-X",                           "Bar-headed Goose",                                                                  NA,  "yes",
  "A213",                                   "Barn Owl",                                                                  NA,  "yes",
  "A251",                               "Barn Swallow",                                                                  NA,  "yes",
  "A045-X",                             "Barnacle Goose",                                            "non-native populations",   "no",
  "A045-A",                             "Barnacle Goose",                                 "East Greenland/Scotland & Ireland",   "no",
  "A045-B",                             "Barnacle Goose",                                      "Svalbard/South-west Scotland",   "no",
  "A045-B",                   "Barnacle Goose, Svalbard",                                                                  NA,  "yes",
  "A157",                          "Bar-tailed Godwit",                                                                  NA,  "yes",
  "A701",                                 "Bean Goose",                                             "Anser fabalis fabalis",   "no",
  "A702",                                 "Bean Goose",                                            "Anser fabalis rossicus",   "no",
  "A701",                          "Bean Goose, Taiga",                                                                  NA,  "yes",
  "A323",                         "Bearded Parrotbill",                                                                  NA,  "yes",
  "A037",                              "Bewick's Swan",                                                                  NA,  "yes",
  "A877",                               "Black Grouse",                                                                  NA,  "yes",
  "A202",                            "Black Guillemot",                                                                  NA,  "yes",
  "A273",                             "Black Redstart",                                                                  NA,  "yes",
  "A747-X",                                 "Black Swan",                                                                  NA,  "yes",
  "A197",                                 "Black Tern",                                                                  NA,  "yes",
  "A343",                        "Black-billed Magpie",                                                                  NA,  "yes",
  "A311",                                   "Blackcap",                                                                  NA,  "yes",
  "A179",                          "Black-headed Gull",                                                                  NA,  "yes",
  "A188",                     "Black-legged Kittiwake",                                                                  NA,  "yes",
  "A008",                         "Black-necked Grebe",                                                                  NA,  "yes",
  "A616",                        "Black-tailed Godwit",                                           "Limosa limosa islandica",   "no",
  "A614-A",                        "Black-tailed Godwit",            "Limosa limosa limosa,  Western Europe/NW & West Africa",   "no",
  "A156",                        "Black-tailed Godwit",                       "Limosa limosa, all non-breeding populations",   "no",
  "A616",              "Black-tailed Godwit islandica",                                                                  NA,  "yes",
  "A614-A",                 "Black-tailed Godwit limosa",                                                                  NA,  "yes",
  "A002",                       "Black-throated Diver",                                                                  NA,  "yes",
  "A131",                         "Black-winged Stilt",                                                                  NA,  "yes",
  "A483",                                   "Blue Tit",                                                                  NA,  "yes",
  "A360",                                  "Brambling",                                                                  NA,  "yes",
  "A675",                                "Brent Goose",                            "Branta bernicla bernicla, Dark-bellied",   "no",
  "A674-A",                                "Brent Goose",  "Branta bernicla hrota, Canada & Greenland/Ireland, Light-bellied",   "no",
  "A674-B",                                "Brent Goose",       "Branta bernicla hrota, Svalbard/Denmark & UK, Light-bellied",   "no",
  "A044-X",                               "Canada Goose",                                                                  NA,  "yes",
  "A674-A",         "Canadian Light-bellied Brent Goose",                                                                  NA,  "yes",
  "A349",                               "Carrion Crow",                                                                  NA,  "yes",
  "A025",                               "Cattle Egret",                                                                  NA,  "yes",
  "A288",                            "Cetti's Warbler",                                                                  NA,  "yes",
  "A377",                               "Cirl Bunting",                                                                  NA,  "yes",
  "A472",                                   "Coal Tit",                                                                  NA,  "yes",
  "A087",                             "Common Buzzard",                                                                  NA,  "yes",
  "A572",                          "Common Chiffchaff",                                                                  NA,  "yes",
  "A125",                                "Common Coot",                                                                  NA,  "yes",
  "A127",                               "Common Crane",                                                                  NA,  "yes",
  "A212",                              "Common Cuckoo",                                                                  NA,  "yes",
  "A063",                               "Common Eider",                                                                  NA,  "yes",
  "A067",                           "Common Goldeneye",                                                                  NA,  "yes",
  "A290",                 "Common Grasshopper-warbler",                                                                  NA,  "yes",
  "A164",                          "Common Greenshank",                                                                  NA,  "yes",
  "A887",                           "Common Guillemot",                                                                  NA,  "yes",
  "A887",                     "Common Guillemot aalge",                                                                  NA,  "yes",
  "A887",                  "Common Guillemot albionis",                                                                  NA,  "yes",
  "A182",                                "Common Gull",                                                                  NA,  "yes",
  "A096",                             "Common Kestrel",                                                                  NA,  "yes",
  "A229",                          "Common Kingfisher",                                                                  NA,  "yes",
  "A070",                           "Common Merganser",                                                                  NA,  "yes",
  "A123",                             "Common Moorhen",                                                                  NA,  "yes",
  "A271",                         "Common Nightingale",                                                                  NA,  "yes",
  "A115-X",                            "Common Pheasant",                                                                  NA,  "yes",
  "A059",                             "Common Pochard",                                                                  NA,  "yes",
  "A113",                               "Common Quail",                                                                  NA,  "yes",
  "A350",                               "Common Raven",                                                                  NA,  "yes",
  "A474",                             "Common Redpoll",                                                                  NA,  "yes",
  "A162",                            "Common Redshank",                                                                  NA,  "yes",
  "A274",                            "Common Redstart",                                                                  NA,  "yes",
  "A137",                       "Common Ringed Plover",                                                                  NA,  "yes",
  "A168",                           "Common Sandpiper",                                                                  NA,  "yes",
  "A900",                              "Common Scoter",                                                                  NA,  "yes",
  "A048",                            "Common Shelduck",                                                                  NA,  "yes",
  "A153",                               "Common Snipe",                                                                  NA,  "yes",
  "A351",                            "Common Starling",                                                                  NA,  "yes",
  "A276",                           "Common Stonechat",                                                                  NA,  "yes",
  "A226",                               "Common Swift",                                                                  NA,  "yes",
  "A226",                              "Common Swift,",                                                                  NA,  "yes",
  "A052",                                "Common Teal",                                                                  NA,  "yes",
  "A193",                                "Common Tern",                                                                  NA,  "yes",
  "A309",                         "Common Whitethroat",                                                                  NA,  "yes",
  "A687",                         "Common Wood-pigeon",                                                                  NA,  "yes",
  "A383",                               "Corn Bunting",                                                                  NA,  "yes",
  "A122",                                  "Corncrake",                                                                  NA,  "yes",
  "A497",                                "Crested Tit",                                                                  NA,  "yes",
  "A675",                   "Dark-bellied Brent Geese",                                                                  NA,  "yes",
  "A302",                           "Dartford Warbler",                                                                  NA,  "yes",
  "A466-A",                                     "Dunlin", "Calidris alpina schinzii, Britain & Ireland/SW Europe & NW Africa",   "no",
  "A149",                                     "Dunlin",                     "Calidris alpina, all non-breeding populations",   "no",
  "A149",                              "Dunlin alpina",                                                                  NA,  "yes",
  "A466-A",                            "Dunlin schinzii",                                                                  NA,  "yes",
  "A215-X",                                  "Eagle Owl",                                                                  NA,  "yes",
  "A748-X",                             "Egyptian Goose",                                                                  NA,  "yes",
  "A844-X",                              "Emperor Goose",                                                                  NA,  "yes",
  "A283",                         "Eurasian Blackbird",                                                                  NA,  "yes",
  "A372",                         "Eurasian Bullfinch",                                                                  NA,  "yes",
  "A657",                         "Eurasian Chaffinch",                                                                  NA,  "yes",
  "A209",                     "Eurasian Collared Dove",                                                                  NA,  "yes",
  "A209",                     "Eurasian Collared-dove",                                                                  NA,  "yes",
  "A768",                            "Eurasian Curlew",                                                                  NA,  "yes",
  "A727",                          "Eurasian Dotterel",                                                                  NA,  "yes",
  "A337",                     "Eurasian Golden Oriole",                                                                  NA,  "yes",
  "A140",                     "Eurasian Golden Plover",                                                                  NA,  "yes",
  "A140",                    "Eurasian Golden Plover,",                                                                  NA,  "yes",
  "A866",                  "Eurasian Green Woodpecker",                                                                  NA,  "yes",
  "A099",                             "Eurasian Hobby",                                                                  NA,  "yes",
  "A347",                           "Eurasian Jackdaw",                                                                  NA,  "yes",
  "A342",                               "Eurasian Jay",                                                                  NA,  "yes",
  "A476",                            "Eurasian Linnet",                                                                  NA,  "yes",
  "A224",                          "Eurasian Nightjar",                                                                  NA,  "yes",
  "A130",                     "Eurasian Oystercatcher",                                                                  NA,  "yes",
  "A297",                      "Eurasian Reed-warbler",                                                                  NA,  "yes",
  "A478",                            "Eurasian Siskin",                                                                  NA,  "yes",
  "A247",                           "Eurasian Skylark",                                                                  NA,  "yes",
  "A898",                       "Eurasian Sparrowhawk",                                                                  NA,  "yes",
  "A034",                         "Eurasian Spoonbill",                                                                  NA,  "yes",
  "A133",                        "Eurasian Thick-knee",                                                                  NA,  "yes",
  "A356",                      "Eurasian Tree Sparrow",                                                                  NA,  "yes",
  "A334",                       "Eurasian Treecreeper",                                                                  NA,  "yes",
  "A855",                            "Eurasian Wigeon",                                                                  NA,  "yes",
  "A155",                          "Eurasian Woodcock",                                                                  NA,  "yes",
  "A233",                           "Eurasian Wryneck",                                                                  NA,  "yes",
  "A364",                         "European Goldfinch",                                                                  NA,  "yes",
  "A363",                        "European Greenfinch",                                                                  NA,  "yes",
  "A072",                     "European Honey-buzzard",                                                                  NA,  "yes",
  "A322",                   "European Pied Flycatcher",                                                                  NA,  "yes",
  "A269",                             "European Robin",                                                                  NA,  "yes",
  "A684",                              "European Shag",                                                                  NA,  "yes",
  "A014",                      "European Storm-petrel",                                                                  NA,  "yes",
  "A210",                       "European Turtle-dove",                                                                  NA,  "yes",
  "A394",               "European White-fronted Goose",                                                                  NA,  "yes",
  "A434",                             "Fair Isle Wren",                                                                  NA,  "yes",
  "A284",                                  "Fieldfare",                                                                  NA,  "yes",
  "A318",                                  "Firecrest",                                                                  NA,  "yes",
  "A009",                                     "Fulmar",                                                                  NA,  "yes",
  "A889",                                    "Gadwall",                                                                  NA,  "yes",
  "A310",                             "Garden Warbler",                                                                  NA,  "yes",
  "A856",                                   "Garganey",                                                                  NA,  "yes",
  "A186",                              "Glaucous Gull",                                                                  NA,  "yes",
  "A317",                                  "Goldcrest",                                                                  NA,  "yes",
  "A091",                               "Golden Eagle",                                                                  NA,  "yes",
  "A337",                              "Golden Oriole",                                                                  NA,  "yes",
  "A557-X",                            "Golden Pheasant",                                                                  NA,  "yes",
  "A021",                              "Great Bittern",                                                                  NA,  "yes",
  "A187",                    "Great Black-backed Gull",                                                                  NA,  "yes",
  "A683",                            "Great Cormorant",                                         "Phalacrocorax carbo carbo",   "no",
  "A391",                            "Great Cormorant",                                      "Phalacrocorax carbo sinensis",   "no",
  "A683",                      "Great Cormorant carbo",                                                                  NA,  "yes",
  "A391",                   "Great Cormorant sinensis",                                                                  NA,  "yes",
  "A005",                        "Great Crested Grebe",                                                                  NA,  "yes",
  "A003",                       "Great Northern Diver",                                                                  NA,  "yes",
  "A175",                                 "Great Skua",                                                                  NA,  "yes",
  "A658",                   "Great Spotted Woodpecker",                                                                  NA,  "yes",
  "A330",                                  "Great Tit",                                                                  NA,  "yes",
  "A773",                          "Great White Egret",                                                                  NA,  "yes",
  "A062",                              "Greater Scaup",                                                                  NA,  "yes",
  "A165",                            "Green Sandpiper",                                                                  NA,  "yes",
  "A045-A",                   "Greenland Barnacle Goose",                                                                  NA,  "yes",
  "A395",              "Greenland White-fronted Goose",                                                                  NA,  "yes",
  "A028",                                 "Grey Heron",                                                                  NA,  "yes",
  "A644",                             "Grey Partridge",                                                                  NA,  "yes",
  "A141",                                "Grey Plover",                                                                  NA,  "yes",
  "A261",                               "Grey Wagtail",                                                                  NA,  "yes",
  "A043",                              "Greylag Goose",                                                                  NA,  "yes",
  "A043",                    "Greylag Goose (Iceland)",                                                                  NA,  "yes",
  "A043",                         "Greylag Goose (UK)",                                                                  NA,  "yes",
  "A847-X",                              "Harris's Hawk",                                                                  NA,  "yes",
  "A373",                                   "Hawfinch",                                                                  NA,  "yes",
  "A266",                             "Hedge Accentor",                                                                  NA,  "yes",
  "A757-X",                        "Helmeted Guineafowl",                                                                  NA,  "yes",
  "A082",                                "Hen Harrier",                                                                  NA,  "yes",
  "A895",                               "Herring Gull",                                                                  NA,  "yes",
  "A349",                                "Hooded Crow",                                                                  NA,  "yes",
  "A007",                               "Horned Grebe",                                                                  NA,  "yes",
  "A620",                              "House Sparrow",                                                                  NA,  "yes",
  "A185",                               "Iceland Gull",                                                                  NA,  "yes",
  "A756-X",                             "Indian Peafowl",                                                                  NA,  "yes",
  "A152",                                 "Jack Snipe",                                                                  NA,  "yes",
  "A755-X",                    "Lady Amherst's Pheasant",                                                                  NA,  "yes",
  "A854",                       "Leach's Storm-petrel",                                                                  NA,  "yes",
  "A489",                   "Lesser Black-backed Gull",                                                                  NA,  "yes",
  NA,                             "Lesser Redpoll",                                                                  NA,   "no",
  "A869",                  "Lesser Spotted Woodpecker",                                                                  NA,  "yes",
  "A574",                         "Lesser Whitethroat",                                                                  NA,  "yes",
  "A203",                                 "Little Auk",                                                                  NA,  "yes",
  "A022",                             "Little Bittern",                                                                  NA,  "yes",
  "A026",                               "Little Egret",                                                                  NA,  "yes",
  "A004",                               "Little Grebe",                                                                  NA,  "yes",
  "A862",                                "Little Gull",                                                                  NA,  "yes",
  "A218-X",                                 "Little Owl",                                                                  NA,  "yes",
  "A136",                       "Little Ringed Plover",                                                                  NA,  "yes",
  "A885",                                "Little Tern",                                                                  NA,  "yes",
  "A221",                             "Long-eared Owl",                                                                  NA,  "yes",
  "A064",                           "Long-tailed Duck",                                                                  NA,  "yes",
  "A324",                            "Long-tailed Tit",                                                                  NA,  "yes",
  "A053",                                    "Mallard",                                                                  NA,  "yes",
  "A553-X",                              "Mandarin Duck",                                                                  NA,  "yes",
  "A013",                            "Manx Shearwater",                                                                  NA,  "yes",
  "A493",                                  "Marsh Tit",                                                                  NA,  "yes",
  "A296",                              "Marsh Warbler",                                                                  NA,  "yes",
  "A257",                               "Meadow Pipit",                                                                  NA,  "yes",
  "A176",                         "Mediterranean Gull",                                                                  NA,  "yes",
  "A098",                                     "Merlin",                                                                  NA,  "yes",
  "A182",                                   "Mew Gull",                                                                  NA,  "yes",
  "A287",                              "Mistle Thrush",                                                                  NA,  "yes",
  "A761-X",                              "Monk Parakeet",                                                                  NA,  "yes",
  "A084",                          "Montagu's Harrier",                                                                  NA,  "yes",
  "A751-X",                               "Muscovy Duck",                                                                  NA,  "yes",
  "A036",                                  "Mute Swan",                                                                  NA,  "yes",
  "A016",                            "Northern Gannet",                                                                  NA,  "yes",
  "A899",                           "Northern Goshawk",                                                                  NA,  "yes",
  "A738",                      "Northern House-martin",                                                                  NA,  "yes",
  "A142",                           "Northern Lapwing",                                                                  NA,  "yes",
  "A054",                           "Northern Pintail",                                                                  NA,  "yes",
  "A857",                          "Northern Shoveler",                                                                  NA,  "yes",
  "A277",                          "Northern Wheatear",                                                                  NA,  "yes",
  "A094",                                     "Osprey",                                                                  NA,  "yes",
  "A173",                           "Parasitic Jaeger",                                                                  NA,  "yes",
  "A370",                           "Parrot Crossbill",                                                                  NA,  "yes",
  "A103",                                  "Peregrine",                                                                  NA,  "yes",
  "A103",                           "Peregrine Falcon",                                                                  NA,  "yes",
  "A132",                                "Pied Avocet",                                                                  NA,  "yes",
  "A040-B",                          "Pink-footed Goose",                                                                  NA,  "yes",
  "A148",                           "Purple Sandpiper",                                                                  NA,  "yes",
  "A200",                                  "Razorbill",                                                                  NA,  "yes",
  "A369",                              "Red Crossbill",                                                                  NA,  "yes",
  "A074",                                   "Red Kite",                                                                  NA,  "yes",
  "A143",                                   "Red Knot",                                                                  NA,  "yes",
  "A338",                          "Red-backed Shrike",                                                                  NA,  "yes",
  "A346",                          "Red-billed Chough",                                                                  NA,  "yes",
  "A069",                     "Red-breasted Merganser",                                                                  NA,  "yes",
  "A058-X",                        "Red-crested Pochard",                                                                  NA,  "yes",
  "A110-X",                       "Red-legged Partridge",                                                                  NA,  "yes",
  "A006",                           "Red-necked Grebe",                                                                  NA,  "yes",
  "A170",                       "Red-necked Phalarope",                                                                  NA,  "yes",
  "A846-X",                            "Red-tailed Hawk",                                                                  NA,  "yes",
  "A001",                         "Red-throated Diver",                                                                  NA,  "yes",
  "A286",                                    "Redwing",                                                                  NA,  "yes",
  "A381",                               "Reed Bunting",                                                                  NA,  "yes",
  "A558-X",                          "Reeves's Pheasant",                                                                  NA,  "yes",
  "A282",                                 "Ring Ouzel",                                                                  NA,  "yes",
  "A206",                                  "Rock Dove",                                                                  NA,  "yes",
  "A206-X",                                "Rock Pigeon",                                                 "feral populations",   "no",
  "A206",                                "Rock Pigeon",                                                  "wild populations",   "no",
  "A666",                                 "Rock Pipit",                                                                  NA,  "yes",
  "A891",                             "Rock Ptarmigan",                                                                  NA,  "yes",
  "A348",                                       "Rook",                                                                  NA,  "yes",
  "A192",                               "Roseate Tern",                                                                  NA,  "yes",
  "A760-X",                       "Rose-ringed Parakeet",                                                                  NA,  "yes",
  "A848-X",                        "Rosy-faced Lovebird",                                                                  NA,  "yes",
  "A750-X",                                 "Ruddy Duck",                                                                  NA,  "yes",
  "A397-X",                             "Ruddy Shelduck",                                                                  NA,  "yes",
  "A169",                            "Ruddy Turnstone",                                                                  NA,  "yes",
  "A861",                                       "Ruff",                                                                  NA,  "yes",
  "A249",                                "Sand Martin",                                                                  NA,  "yes",
  "A144",                                 "Sanderling",                                                                  NA,  "yes",
  "A863",                              "Sandwich Tern",                                                                  NA,  "yes",
  "A292",                             "Savi's Warbler",                                                                  NA,  "yes",
  "A451",                         "Scottish Crossbill",                                                                  NA,  "yes",
  "A295",                              "Sedge Warbler",                                                                  NA,  "yes",
  "A222",                            "Short-eared Owl",                                                                  NA,  "yes",
  "A767",                                       "Smew",                                                                  NA,  "yes",
  "A375",                               "Snow Bunting",                                                                  NA,  "yes",
  "A556-X",                                 "Snow Goose",                                                                  NA,  "yes",
  "A285",                                "Song Thrush",                                                                  NA,  "yes",
  "A119",                              "Spotted Crake",                                                                  NA,  "yes",
  "A319",                         "Spotted Flycatcher",                                                                  NA,  "yes",
  "A161",                           "Spotted Redshank",                                                                  NA,  "yes",
  "A207",                                 "Stock Dove",                                                                  NA,  "yes",
  NA,                                "Surf Scoter",                                                                  NA,   "no",
  "A045-B",                    "Svalbard Barnacle Goose",                                                                  NA,  "yes",
  "A674-B",         "Svalbard Light-bellied Brent Geese",                                                                  NA,  "yes",
  "A219",                                  "Tawny Owl",                                                                  NA,  "yes",
  "A146",                           "Temminck's Stint",                                                                  NA,  "yes",
  "A256",                                 "Tree Pipit",                                                                  NA,  "yes",
  "A061",                                "Tufted Duck",                                                                  NA,  "yes",
  "A037",                                "Tundra Swan",                                                                  NA,  "yes",
  "A477",                                      "Twite",                                                                  NA,  "yes",
  "A066",                              "Velvet Scoter",                                                                  NA,  "yes",
  "A118",                                 "Water Rail",                                                                  NA,  "yes",
  "A659",                       "Western Capercaillie",                                                                  NA,  "yes",
  "A081",                     "Western Marsh -harrier",                                                                  NA,  "yes",
  "A081",                      "Western Marsh-harrier",                                                                  NA,  "yes",
  "A158",                                   "Whimbrel",                                                                  NA,  "yes",
  "A275",                                   "Whinchat",                                                                  NA,  "yes",
  "A275",                       "White (Pied) Wagtail",                                                                  NA,  "yes",
  "A262",                              "White Wagtail",                                                                  NA,  "yes",
  "A502",                         "White-billed Diver",                                                                  NA,  "yes",
  "A075",                         "White-tailed Eagle",                                                                  NA,  "yes",
  "A264",                      "White-throated Dipper",                                                                  NA,  "yes",
  "A038",                               "Whooper Swan",                                                                  NA,  "yes",
  "A460-X",                                "Wild Turkey",                                                                  NA,  "yes",
  "A463",                           "Willow Ptarmigan",                                         "Lagopus lagopus hibernica",   "no",
  "A711",                           "Willow Ptarmigan",                                           "Lagopus lagopus scotica",   "no",
  "A463", "Willow Ptarmigan (Red Grouse) (hibernicus)",                                                                  NA,  "yes",
  "A711",    "Willow Ptarmigan (Red Grouse) (scotica)",                                                                  NA,  "yes",
  "A711",   "Willow Ptarmigan (Red Grouse) (scoticus)",                                                                  NA,  "yes",
  "A492",                                 "Willow Tit",                                                                  NA,  "yes",
  "A316",                             "Willow Warbler",                                                                  NA,  "yes",
  "A676",                                "Winter Wren",                                "Troglodytes troglodytes all others",   "no",
  "A434",                                "Winter Wren",                              "Troglodytes troglodytes fridariensis",   "no",
  "A749-X",                                  "Wood Duck",                                                                  NA,  "yes",
  "A246",                                  "Wood Lark",                                                                  NA,  "yes",
  "A332",                              "Wood Nuthatch",                                                                  NA,  "yes",
  "A166",                             "Wood Sandpiper",                                                                  NA,  "yes",
  "A314",                               "Wood Warbler",                                                                  NA,  "yes",
  "A260",                             "Yellow Wagtail",                                                                  NA,  "yes",
  "A376",                               "Yellowhammer",                                                                  NA,  "yes"
)



